INSERT INTO games ( title, developer, description, price, discount_price, platform, genre, release_date, is_active, image_url)
VALUES
    ('Elden Ring', 'FromSoftware', 'Open-world action RPG set in the Lands Between.', 59.99, 39.99, 'PC', 'RPG', '2022-02-25', TRUE, 'https://example.com/eldenring.jpg'),
    ( 'Cyberpunk 2077', 'CD Projekt Red', 'Futuristic open-world RPG in Night City.', 49.99, 29.99, 'PC', 'RPG', '2020-12-10', TRUE, 'https://example.com/cyberpunk2077.jpg'),
    ( 'The Witcher 3: Wild Hunt', 'CD Projekt Red', 'Fantasy RPG with rich storytelling.', 39.99, 19.99, 'PC', 'RPG', '2015-05-19', TRUE, 'https://example.com/witcher3.jpg'),
    ( 'God of War Ragnarök', 'Santa Monica Studio', 'Action adventure based on Norse mythology.', 69.99, 59.99, 'PS5', 'Action', '2022-11-09', TRUE, 'https://example.com/gow_ragnarok.jpg'),
    ( 'Halo Infinite', '343 Industries', 'First-person shooter in the Halo series.', 59.99, 49.99, 'Xbox', 'Shooter', '2021-12-08', TRUE, 'https://example.com/halo_infinite.jpg'),
    ( 'Minecraft', 'Mojang', 'Sandbox block-building game.', 29.99, 19.99, 'PC', 'Sandbox', '2011-11-18', TRUE, 'https://example.com/minecraft.jpg'),
    ( 'FIFA 24', 'EA Sports', 'Football simulation game.', 69.99, 59.99, 'PC', 'Sports', '2023-09-29', TRUE, 'https://example.com/fifa24.jpg'),
    ( 'Hades', 'Supergiant Games', 'Roguelike dungeon crawler.', 24.99, 14.99, 'PC', 'Roguelike', '2020-09-17', TRUE, 'https://example.com/hades.jpg'),
    ( 'Red Dead Redemption 2', 'Rockstar Games', 'Epic tale of life in America’s unforgiving heartland.', 59.99, 29.99, 'PC', 'Action', '2018-10-26', TRUE, 'https://example.com/rdr2.jpg'),
    ( 'Grand Theft Auto V', 'Rockstar Games', 'Open-world action game set in Los Santos.', 29.99, 14.99, 'PC', 'Action', '2013-09-17', TRUE, 'https://example.com/gtav.jpg'),
    ( 'League of Legends', 'Riot Games', 'Multiplayer online battle arena (MOBA).', 0.00, 0.00, 'PC', 'Strategy', '2009-10-27', TRUE, 'https://example.com/lol.jpg'),
    ( 'Valorant', 'Riot Games', 'Tactical hero-based FPS.', 0.00, 0.00, 'PC', 'Shooter', '2020-06-02', TRUE, 'https://example.com/valorant.jpg'),
    ( 'Overwatch 2', 'Blizzard Entertainment', 'Team-based hero shooter.', 0.00, 0.00, 'PC', 'Shooter', '2022-10-04', TRUE, 'https://example.com/overwatch2.jpg'),
    ( 'Fortnite', 'Epic Games', 'Battle royale game with building mechanics.', 0.00, 0.00, 'PC', 'Shooter', '2017-07-21', TRUE, 'https://example.com/fortnite.jpg'),
    ( 'Apex Legends', 'Respawn Entertainment', 'Battle royale hero shooter.', 0.00, 0.00, 'PC', 'Shooter', '2019-02-04', TRUE, 'https://example.com/apex.jpg'),
    ( 'Call of Duty: Modern Warfare II', 'Infinity Ward', 'First-person military shooter.', 69.99, 49.99, 'PC', 'Shooter', '2022-10-28', TRUE, 'https://example.com/cod_mw2.jpg'),
    ( 'Resident Evil 4 Remake', 'Capcom', 'Survival horror remake of classic RE4.', 59.99, 44.99, 'PC', 'Action', '2023-03-24', TRUE, 'https://example.com/re4_remake.jpg'),
    ( 'Monster Hunter: World', 'Capcom', 'Hunt giant monsters in living ecosystems.', 29.99, 19.99, 'PC', 'Action', '2018-01-26', TRUE, 'https://example.com/mhw.jpg'),
    ('Dark Souls III', 'FromSoftware', 'Challenging dark fantasy RPG.', 59.99, 19.99, 'PC', 'RPG', '2016-04-12', TRUE, 'https://example.com/ds3.jpg'),
    ( 'Sekiro: Shadows Die Twice', 'FromSoftware', 'Action-adventure with intense sword combat.', 59.99, 39.99, 'PC', 'Action', '2019-03-22', TRUE, 'https://example.com/sekiro.jpg');
INSERT INTO games ( title, developer, description, price, discount_price, platform, genre, release_date, is_active, image_url)
VALUES
-- 已给的 1-20
( 'Stardew Valley', 'ConcernedApe', 'Farming and life simulation indie hit.', 14.99, 9.99, 'PC', 'Simulation', '2016-02-26', TRUE, 'https://example.com/stardew.jpg'),
('Terraria', 'Re-Logic', '2D sandbox adventure game.', 9.99, 4.99, 'PC', 'Sandbox', '2011-05-16', TRUE, 'https://example.com/terraria.jpg'),
( 'Celeste', 'Maddy Makes Games', 'Challenging platformer about climbing a mountain.', 19.99, 9.99, 'PC', 'Platformer', '2018-01-25', TRUE, 'https://example.com/celeste.jpg'),
('Hollow Knight', 'Team Cherry', 'Metroidvania adventure in Hallownest.', 14.99, 7.99, 'PC', 'Adventure', '2017-02-24', TRUE, 'https://example.com/hollowknight.jpg'),
( 'Dead Cells', 'Motion Twin', 'Rogue-lite, Metroidvania-inspired action-platformer.', 24.99, 14.99, 'PC', 'Roguelike', '2018-08-07', TRUE, 'https://example.com/deadcells.jpg'),
('Among Us', 'Innersloth', 'Social deduction party game.', 4.99, 2.99, 'PC', 'Party', '2018-06-15', TRUE, 'https://example.com/amongus.jpg'),
('Fall Guys', 'Mediatonic', 'Massive multiplayer party knockout game.', 19.99, 0.00, 'PC', 'Party', '2020-08-04', TRUE, 'https://example.com/fallguys.jpg'),
( 'Cuphead', 'Studio MDHR', 'Run-and-gun action with 1930s cartoon style.', 19.99, 9.99, 'PC', 'Action', '2017-09-29', TRUE, 'https://example.com/cuphead.jpg'),
('Doom Eternal', 'id Software', 'Fast-paced demon-slaying FPS.', 59.99, 29.99, 'PC', 'Shooter', '2020-03-20', TRUE, 'https://example.com/doom_eternal.jpg'),
('Assassin’s Creed Valhalla', 'Ubisoft', 'Open-world Viking RPG.', 59.99, 29.99, 'PC', 'Action', '2020-11-10', TRUE, 'https://example.com/ac_valhalla.jpg'),
( 'Far Cry 6', 'Ubisoft', 'First-person shooter set in a fictional Caribbean island.', 59.99, 39.99, 'PC', 'Shooter', '2021-10-07', TRUE, 'https://example.com/farcry6.jpg'),
( 'Destiny 2', 'Bungie', 'Online-only multiplayer FPS with MMO elements.', 0.00, 0.00, 'PC', 'Shooter', '2017-09-06', TRUE, 'https://example.com/destiny2.jpg'),
('Diablo IV', 'Blizzard Entertainment', 'Dark fantasy action RPG.', 69.99, 59.99, 'PC', 'RPG', '2023-06-05', TRUE, 'https://example.com/diablo4.jpg'),
('Baldur’s Gate 3', 'Larian Studios', 'Turn-based RPG set in Dungeons & Dragons universe.', 59.99, 59.99, 'PC', 'RPG', '2023-08-03', TRUE, 'https://example.com/bg3.jpg'),
( 'Starfield', 'Bethesda Game Studios', 'Open-world space RPG.', 69.99, 59.99, 'PC', 'RPG', '2023-09-06', TRUE, 'https://example.com/starfield.jpg'),
( 'The Legend of Zelda: Breath of the Wild', 'Nintendo', 'Open-world adventure game.', 59.99, 59.99, 'Switch', 'Adventure', '2017-03-03', TRUE, 'https://example.com/zelda_botw.jpg'),
('The Legend of Zelda: Tears of the Kingdom', 'Nintendo', 'Sequel to BOTW with expanded gameplay.', 69.99, 69.99, 'Switch', 'Adventure', '2023-05-12', TRUE, 'https://example.com/zelda_totk.jpg'),
( 'Super Mario Odyssey', 'Nintendo', '3D platformer featuring Mario’s globe-trotting adventure.', 59.99, 49.99, 'Switch', 'Platformer', '2017-10-27', TRUE, 'https://example.com/mario_odyssey.jpg'),
('Super Smash Bros. Ultimate', 'Nintendo', 'Crossover fighting game.', 59.99, 59.99, 'Switch', 'Fighting', '2018-12-07', TRUE, 'https://example.com/smash.jpg'),
( 'Splatoon 3', 'Nintendo', 'Multiplayer shooter with ink mechanics.', 59.99, 49.99, 'Switch', 'Shooter', '2022-09-09', TRUE, 'https://example.com/splatoon3.jpg'),
-- 补充虚拟 41-50
('Galaxy Raiders', 'IndieForge Studio', 'Space-themed rogue-lite adventure.', 19.99, 9.99, 'PC', 'Roguelike', '2021-06-01', TRUE, 'https://example.com/galaxy_raiders.jpg'),
( 'Shadow Realm', 'PhantomWorks', 'Dark fantasy action RPG with open dungeons.', 39.99, 24.99, 'PC', 'RPG', '2022-02-14', TRUE, 'https://example.com/shadow_realm.jpg'),
( 'Neon Streets', 'NeonByte Games', 'Cyberpunk racing and shooting hybrid.', 29.99, 19.99, 'PC', 'Racing', '2023-04-20', TRUE, 'https://example.com/neon_streets.jpg'),
('Battle Mechs Arena', 'IronCore Studio', 'Multiplayer mech combat game.', 49.99, 34.99, 'PC', 'Shooter', '2021-09-09', TRUE, 'https://example.com/battle_mechs.jpg'),
( 'Ancient Myths Online', 'Mythos Devs', 'MMORPG inspired by Greek and Norse mythology.', 0.00, 0.00, 'PC', 'RPG', '2020-08-15', TRUE, 'https://example.com/ancient_myths.jpg'),
('City Builder Tycoon', 'UrbanSoft', 'Simulation game to build and manage cities.', 39.99, 19.99, 'PC', 'Simulation', '2019-03-11', TRUE, 'https://example.com/citybuilder.jpg'),
('Dragonfire Saga', 'RedPeak Games', 'Fantasy RPG with turn-based combat.', 49.99, 29.99, 'PC', 'RPG', '2022-11-22', TRUE, 'https://example.com/dragonfire.jpg'),
('Skyborne Heroes', 'CloudNine Studio', 'Action adventure with flying mechanics.', 44.99, 24.99, 'PC', 'Action', '2021-05-30', TRUE, 'https://example.com/skyborne.jpg'),
('Quantum Tactics', 'FutureMind', 'Sci-fi tactical RPG with time manipulation.', 59.99, 39.99, 'PC', 'Strategy', '2023-07-18', TRUE, 'https://example.com/quantum_tactics.jpg'),
( 'Legends Reborn', 'EternalForge', 'Fantasy MMORPG with large-scale raids.', 0.00, 0.00, 'PC', 'RPG', '2024-01-12', TRUE, 'https://example.com/legends_reborn.jpg');
